
ALTER TABLE "accounts" DROP COLUMN IF EXISTS account_type;
ALTER TABLE "accounts" DROP COLUMN IF EXISTS product_type;
ALTER TABLE "accounts DROP CONSTRAINT IF EXISTS "accounts_owner_fkey";
DROP TYPE IF EXISTS ACCOUNTS_ENUM;
DROP TYPE IF EXISTS PRODUCTS_ENUM;
DROP TABLE IF EXISTS "users";
