
ALTER TABLE IF EXISTS "accounts" DROP COLUMN account_type;
ALTER TABLE IF EXISTS "accounts" DROP COLUMN product_type;
DROP TYPE IF EXISTS ACCOUNTS_ENUM;
DROP TYPE IF EXISTS PRODUCTS_ENUM;
ALTER TABLE IF EXISTS "accounts" DROP CONSTRAINT IF EXISTS "owner_currency_key";
ALTER TABLE IF EXISTS "accounts" DROP CONSTRAINT IF EXISTS "accounts_owner_fkey";
DROP TABLE IF EXISTS "users";

