
ALTER TABLE IF EXISTS "accounts" DROP COLUMN account_type;
ALTER TABLE IF EXISTS "accounts" DROP COLUMN product_type;
ALTER TABLE IF EXISTS DROP CONSTRAINT IF EXISTS "accounts_owner_fkey";
DROP TYPE IF EXISTS ACCOUNTS_ENUM;
DROP TYPE IF EXISTS PRODUCTS_ENUM;
DROP TABLE IF EXISTS "users";
