ALTER TABLE "accounts"
	DROP CONSTRAINT IF EXISTS "accounts_product_id_fkey";

DROP TABLE IF EXISTS "products";

DROP TYPE IF EXISTS ACCOUNTS_ENUM;
DROP TYPE IF EXISTS PRODUCTS_ENUM;
DROP TYPE IF EXISTS accounts_enum;
DROP TYPE IF EXISTS products_enum;
DROP TYPE IF EXISTS PRODUCT_TYPE_ENUM;

ALTER TABLE "accounts"
	DROP COLUMN IF EXISTS "product_id";
